"""empty message

Revision ID: 42d3ea1be89f
Revises: 
Create Date: 2021-01-12 19:44:11.644643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42d3ea1be89f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identificacion', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=True),
    sa.Column('password', sa.String(length=94), nullable=True),
    sa.Column('direccion', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('servicios_medicos', sa.ARRAY(sa.String(length=30)), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('change_first_password', sa.Boolean(), nullable=True),
    sa.Column('telefono', sa.BigInteger(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('identificacion'),
    sa.UniqueConstraint('username')
    )
    op.create_table('especialidades_medico_paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medico', sa.Integer(), nullable=True),
    sa.Column('paciente', sa.String(length=80), nullable=True),
    sa.Column('especilidades', sa.ARRAY(sa.String(length=80)), nullable=True),
    sa.ForeignKeyConstraint(['medico'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('especialidades_medico_paciente')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
